### PR TITLE
Make the request property read-only — refs cyclejs/core#232

### PR DESCRIPTION
**Pull request by chadrien**

### CODE REVIEW

**Comment by chadrien** [comment]
Travis output:

```
src/http-driver.js
  4:1  warning  Function 'optionsToSuperagent' has a complexity of 16  complexity
```
This is already in master

```
/home/travis/build/cyclejs/http/node_modules/zuul/bin/zuul:328
            throw err.message;
                     ^
firefox@40: [init({"build":"101","name":"@cycle/http","tags":[],"browserName":"firefox","version":"40","platform":"Mac 10.10","appium-version":"1"})] The environment you requested was unavailable.: Sauce Labs Authentication Error.
```
Momentary communication error with sauce labs?

Any way to re-trigger the build?

**Comment by staltz** [comment]
> `4:1  warning  Function 'optionsToSuperagent' has a complexity of 16  complexity`

Yeah that's an old one that always happens, don't bother it.

About Travis failing, it's about authentication. We got it working for DOM repo, just need to do the same for this repo. Don't worry, I'll solve this part.

**Comment by chadrien** [comment]
:+1:

**Comment by staltz** [comment]
Merged! Thanks!
The tests passed when I ran them manually. There's something wrong with iphone simulators in saucelabs, but that's not about this PR.

**Comment by chadrien** [comment]
Yay~

**Pull request merged**
